### ISSUE TITLE
why it's not possible to generate principals and their keytabs in my case ?

### ISSUE THREAD

**Issue by simoni1100** [ist-dsi/kadmin#2]
When I try to add principal and create keytab for a Kafka client I get no result but I have any error in the code.
here is the code:
 ```scala
import com.typesafe.config.ConfigFactory
import pt.tecnico.dsi.kadmin._

object appMain extends App {

  import com.typesafe.config.Config
  import com.typesafe.config.ConfigFactory

  val conf = ConfigFactory.load
  println(conf.getString("kadmin.realm"))
  val kadmi: Kadmin = new Kadmin(conf)

  kadmi.addPrincipal("addprinc", "clie/kafka.example.com", randKey = true)
  kadmi.createKeytab("ktadd -e des3-cbc-sha1 -kt /home/sliman/cli.keytab", "clie/kafka.example.com")
}
```
and here is my "reference.conf" that i used:
```scala
kadmin {
  realm = "EXAMPLE.COM"

  principal = "kadmin/admin"
  // If keytab is not empty "command-keytab" will be used.
  // If password is not empty "command-password" will be used.
  // If both password and keytab are not empty "command-keytab" will be used.
  keytab = "/etc/krb5.keytab"
  password = ""

  // This is the command used to start kadmin.
  // The literal string "$FULL_PRINCIPAL" will be replaced with s"$principal@$realm"
  // The literal string "$KEYTAB" will be replaced with s"$keytab"
  command-keytab = ${kadmin.command-password}" -kt $KEYTAB"
  command-password = "kadmin -p $FULL_PRINCIPAL"

  //The location to which keytabs will be generated to. Make sure this location:
  // · is NOT volatile
  // · is not world readable
  // · the user running the application has permission to write and to read from it.
  keytabs-location = "/home/sliman"

  //Regex that matches against the kadmin command prompt
  prompt = "kadmin(.local)?: "

  # Kadmin will use as settings for scala-expect library those defined:
  # 1) Here, directly under the path kadmin (these have precedence over the next ones).
  # 2) On the same level as kadmin.
}
```
could you help me please !

**Comment by Lasering** [comment]
You can easily print all the settings with this code:
```scala
val kadmin = new Kadmin()
println(kadmin.settings)
```

The first argument to `addPrincipal` are the options you want to pass directly to the add_principal kadmin command. However it seems you don't want to pass any custom option so you can just do:
```scala
kadmin.addPrincipal("", "clie/kafka.example.com", randKey = true)
```
The `createKeytab` operates on the same principle so you would do:
```scala
kadmin.createKeytab("-e des3-cbc-sha1", "clie/kafka.example.com")
```
The current implementation always creates the keytabs in the same location (defined in the settings using the `keytabs-location`). So after you create the keytab you have to fetch it with `kadmin.obtainKeytab("clie/kafka.example.com")`. 
Since you set the `keytabs-location` to "/home/sliman" the keytab will already be there with the name `clie.kafka.example.com.keytab`.

PS: it seems like a good improvement to allow specifying the location where the keytab will be created.
PS: maybe its misleading to have the first argument to most operations be the "special" options to pass to each command. Do you think that moving the options to the end of the argument list makes the code simpler and more intuitive to use?

**Comment by simoni1100** [comment]
First thank you for your quick reply , when i print all the settings i got the same problem no keytab and principal generated ,here is the code after modification:
```scala
import com.typesafe.config.ConfigFactory
import pt.tecnico.dsi.kadmin._

object appMain extends App {

  import com.typesafe.config.Config
  import com.typesafe.config.ConfigFactory

  val kadmin = new Kadmin()
  println(kadmin.settings)

  kadmin.addPrincipal("", "clie/kafka.example.com", randKey = true)
  kadmin.createKeytab("-e des3-cbc-sha1", "clie/kafka.example.com")
  kadmin.obtainKeytab("clie/kafka.example.com")
}
```
And i got this result when i run this program:

> Kadmin Settings:
> 	Realm: EXAMPLE.COM
> 
> 	Principal: kadmin/admin
> 
> 	Password: 
> 	Keytab: /etc/krb5.keytab
> 
> Keytab authentication will be performed using command:
> 	ArrayBuffer(kadmin, -p, kadmin/admin@EXAMPLE.COM, -kt, /etc/krb5.keytab)
> 
> 	Command keytab: ArrayBuffer(kadmin, -p, kadmin/admin@EXAMPLE.COM, -kt, /etc/krb5.keytab)
> 	Command password: ArrayBuffer(kadmin, -p, kadmin/admin@EXAMPLE.COM)
> 
> 	Keytabs location: /home/sliman
> 
> 	Prompt: "kadmin(.local)?: "
> 
> 	Scala-expect settings:
> 		Timeout: 1 second
> 	
> 		Charset: UTF-8
> 	
> 		Buffer size: 1024 bytes (1 k)
> 	
> 		Redirect StdErr to StdOut: true
> 	     
>      
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/sliman/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/home/sliman/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
> 14:03:26.427 [main] INFO pt.tecnico.dsi.kadmin.Kadmin - Keytab file "/home/sliman/clie.kafka.example.com.keytab" doesn't exist.

**Comment by Lasering** [comment]
The commands `addPrincipal` and `createKeytab` return Futures since the kadmin might take some time to answer the requests. So you need to ensure `createKeytab` is only executed after the `addPrincipal` terminates (maybe using flatMap on the future).

You also need to wait for the "final" future to terminate in order to be able to invoke `obtainKeytab`. However I think you don't need to invoke `obtainKeytab` since it seems like you just want the file and it will already be present in your filesystem.

**Comment by simoni1100** [comment]
I tried to use a single commnad with addPrincippal or deletePrincipal and it did not work it looks like kadmin does not answer the requests ,while delete or add a prinicipal with kadmin in CLI works perfectly.
Any idea to solve the problem please?

**Comment by Lasering** [comment]
Did you wait for the result of the future? Or did you use the code you posted above?
Try this:

```scala
import scala.concurrent.Await
import scala.concurrent.duration.Duration
Await.result(kadmin.addPrincipal("", "clie/kafka.example.com", randKey = true), Duration.Inf)
```

Then check in the cli if the principal was created or not.

**Comment by simoni1100** [comment]
I used a single command but it did not work, i think the problem comes from kadmin which accepts no queries in other way the command "kadmin -p kadmin/admin -kt /etc/krb5.keytab" that kadmin use does not work So automatically I cant add a principal

when i tried your code i got:

> Error:(24, 35) type mismatch;
>  found   : work.martins.simon.expect.core.Expect[Either[pt.tecnico.dsi.kadmin.ErrorCase,Unit]]
>  required: scala.concurrent.Awaitable[?]
>   Await.result(kadmin.addPrincipal("" ,"clie/kafka.example.com" ,randKey = true), Duration.Inf)

I think the problem has no relation with the result of the future as long as the kadmin command mentioned above is not executed

**Comment by Lasering** [comment]
I forgot the `.run()`. It should be
```scala
import scala.concurrent.Await
import scala.concurrent.duration.Duration
Await.result(kadmin.addPrincipal("", "clie/kafka.example.com", randKey = true).run(), Duration.Inf)
```

**Comment by simoni1100** [comment]
It works , thank you !
In fact i want to use a reactive microservice with scala to creat clients as principals and their keytabs for my kafka Cluster 
do you think akka "interface" for kadmin will work in my case ?

**Comment by Lasering** [comment]
Yes, akka-kadmin should solve your problem. You just need to be careful with:

- The machine in which akka-kadmin will run needs to be able to reach the kerberos_master or be running in the same machine as the master.
- Be extra careful in how you deal with the keytabs, since you will most likely need to transfer them via the network, so I would recommend to configure ssl in your akka remote configuration.

The akka-kadmin does exactly-once processing (not the same as exactly-once delivery), which means it needs to journal the messages it receives. However for security reasons the result of [the message `ObtainKeytab`](https://github.com/ist-dsi/akka-kadmin/blob/master/src/main/scala/pt/tecnico/dsi/kadmin/akka/KadminActor.scala#L159) is not journaled, aka the keytabs will not be persisted in the journal.

Please read very carefully the readme of akka-kadmin, since there are some nuances regarding the ChangePassword and in some cases the AddPrincipal messages.

**Comment by simoni1100** [comment]
I suppose that the machine in which akka-kadmin works must be able to reach the kerberos_master must contain the kerberos client configuration file `krb5.conf` with kadmin installed, but if the microservice is started from a client machine I dont need to transfer the keytab i think ?
And any idea to transfer keytabs securely via the network with scala ?

**Comment by Lasering** [comment]
You create a kerberos principal and a keytab for it, then where are you going to use the keytab?

If you configure ssl for akka.remote it should be secure enough to transfer the keytab.

**Comment by simoni1100** [comment]
The keytab will be used by client machines (kafka clients) so it is inevitably to transfer these keytabs, but how can i do it with an API developed scala and more or less secure?

**Comment by simoni1100** [comment]
Any idea or clarification to do this please ?

**Comment by Lasering** [comment]
If you are going to use akka-kadmin, I recomend configuring SSL in akka-remote, this will allow you to transfer the keytabs in a secure way, and it is developed with Scala.

**Comment by simoni1100** [comment]
Finally i used kadmin without akka, I managed to create the principals but the problem is that i have to send the file keytab with a microservice using the framework lagom to receive it by another microservice.
How can i handle the transfer ?

**Comment by Lasering** [comment]
I've never used lagom, so I can't help you there. However all you need to know is how to securely transfer the keytab, since the method `obtainKeytab` will already give the keytab (as an Array[byte]) which you can send through the network, or via a HTTP.

**Comment by simoni1100** [comment]
You mean I can create a principal and instead of using the `createkeytab` method I use `obtainkeytab` which will allow me to send the keytab (as an Array[byte]) ?

**Comment by Lasering** [comment]
You create the principal, then you create the keytab for it (with `createKeytab`), then you don't need to read the keytab file yourself you just invoke the `obtainKeytab` and it will read the keytabfile for you (the result of it being `Array[Byte]`). Which then you can use to easily send the keytab via the network.

**Comment by simoni1100** [comment]
Ok , thank you !

**Comment by simoni1100** [comment]
HI ,I would like to know if it's possible to get a ticket for my client without passing (`kinit`) command line .
please !

**Comment by Lasering** [comment]
You can obtain a ticket for your client with `KadminUtils.obtainTGT` but that invokes `kinit` for you. I don't know a way to get a ticket without invoking `kinit`.

**Comment by simoni1100** [comment]
My question was how I can get a ticket for my client without needing to type `kinit` in CLI ,for me it is not a problem if your function invokes `kinit`.
And Is there a possibility to renew the ticket once and for all ?

**Comment by simoni1100** [comment]
Why i cannot get a ticket for my principal when i run `obtainTGT` like this 
```
override def createPrincipal(username: String, pssw: String): ServiceCall[NotUsed, Done] = ServiceCall {

    val newPassword = Option(pssw)

    Await.result(kadmin.addPrincipal("", username, newPassword).run(), Duration.Inf)
    KadminUtils.obtainTGT("",username,Option(pssw),None)
    req => scala.concurrent.Future.successful(Done)
  }
```
I can create the Principal but I cannot get a ticket for it.

**Comment by Lasering** [comment]
If you as a admin/dev/user want to get a ticket for a principal (your client) you need to invoke `kinit` its the only way. The function `KadminUtils.obtainTGT` does that for you.

As for the _renew forever_ I think kerberos does not allow that. You can change the settings of your kdc and make the lifetime of the ticket a bigger value, but eventually you have to renew the ticket.

**Comment by simoni1100** [comment]
We can use the GSS-API to do a `kinit` and create a login context for it?

**Comment by Lasering** [comment]
Yes via GSS-API you can make a login request to kerberos.

**Comment by simoni1100** [comment]
Yes, I think this is the only way to authenticate my clients Kafka without keytabs because I'm using a JAAS configuration file to do that:
```
KafkaClient {
    com.sun.security.auth.module.Krb5LoginModule required
   	useKeyTab=false
	useTicketCache=true
	doNotPrompt=true
     	serviceName="kafka";
};
```
Can i handle that using only kadmin-API?

**Comment by Lasering** [comment]
No, kadmin-api is not intended to be used for authentications. You should look for SPNEGO authentication using kerberos. Or just browse how to authenticate users via kerberos in java/scala.

**Comment by simoni1100** [comment]
I used kadmin-api for kerberos administration after the authentication is handled by Java authentication and authorization service (JAAS) file:
```
KafkaClient {
    com.sun.security.auth.module.Krb5LoginModule required
   	useKeyTab=false
	useTicketCache=true
	doNotPrompt=true
     	serviceName="kafka";
};
```
You can take a look here` http://docs.confluent.io/current/kafka/sasl.html `for more information about authentication Kafka clients in my case and let me know your feedback ,Thanks !

**Comment by simoni1100** [comment]
Hi again,
I would like to deploy my Lagom microservice that needs kadmin (to create principals for example) in a docker image knowing that I have that my kdc already deployed in another server, I bring to your knowledge that I am new to docker. Thanks in advance!

**Comment by Lasering** [comment]
Having it deployed in a docker container is no different. All you need to do is ensure the code running inside the container can reach the server with the kdc.

**Comment by simoni1100** [comment]
Any idea or example how to configure this microservice so he can reach the server with the kdc and use kadmin from any client machine ?

**Comment by Lasering** [comment]
Have you test it to see if the default docker configuration already does what you want?

**Comment by simoni1100** [comment]
i'm having a problem packaging the microservice as it uses Lagom when i use sbt assembly and run the jar i get there's no main available which is normal as in Lagom there's no main we just run everything with sbt runAll so you have any idea how to package the microservice so i can add it to Dockerfile

**Comment by Lasering** [comment]
I've never used lagom so I can't help you. Try stackoverflow or if they have a gitter channel try there.
